import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import CookieConsent from '@/components/CookieConsent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cursuri',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="has-[section[role='dialog'][data-open='true']]:overflow-hidden transition-all ease-in-out duration-500">
      <body className={`${inter.className} bg-[rgb(var(--background-start-rgb))]`}>
        <Providers>
          {/* Fixed header at the top */}
          <Header />

          {/* Main content area that starts below the header */}
          <div className="pt-8 bg-[rgb(var(--background-start-rgb))] min-h-screen">
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </div>

          {/* Cookie consent banner */}
          <CookieConsent />
        </Providers>
      </body>
    </html>
  )
}
